#!/bin/sh
##########################################################################
# Script for i3blocks that shows the number of updates available on      #
# Arch. It is best used with a systemd timer or crontab entry that will  #
# automatically poll for and download updates. Ideally, this will show   #
# all updates available for the main repos and AUR.                      #
#                                                                        #
# Author: Kyle Laker <kyle@laker.email>                                  #
# Licensed under the MIT License (see the LICENSE file for more info)    #
##########################################################################

# Constants
red="#FF0000"
green="#00FF00"

# Number of available updates
number=$(pacaur -Qu | wc -l)

echo "${number}"
echo "${number}"
if [ ${number} -gt 0 ]; then
    echo "${red}"
else
    echo "${green}"
fi
